/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-13 at 13:39:10 UTC 
 * Modify at your own risk.
 */

package com.farming.app.frontEnd.answersendpoint.model;

/**
 * Model definition for Answers.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the answersendpoint. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Answers extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String answer;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String dislike;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String facebookId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String facebookName;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String isDeleted;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String like;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String questionId;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String topic;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getAnswer() {
    return answer;
  }

  /**
   * @param answer answer or {@code null} for none
   */
  public Answers setAnswer(java.lang.String answer) {
    this.answer = answer;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDislike() {
    return dislike;
  }

  /**
   * @param dislike dislike or {@code null} for none
   */
  public Answers setDislike(java.lang.String dislike) {
    this.dislike = dislike;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFacebookId() {
    return facebookId;
  }

  /**
   * @param facebookId facebookId or {@code null} for none
   */
  public Answers setFacebookId(java.lang.String facebookId) {
    this.facebookId = facebookId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFacebookName() {
    return facebookName;
  }

  /**
   * @param facebookName facebookName or {@code null} for none
   */
  public Answers setFacebookName(java.lang.String facebookName) {
    this.facebookName = facebookName;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Answers setId(java.lang.String id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getIsDeleted() {
    return isDeleted;
  }

  /**
   * @param isDeleted isDeleted or {@code null} for none
   */
  public Answers setIsDeleted(java.lang.String isDeleted) {
    this.isDeleted = isDeleted;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLike() {
    return like;
  }

  /**
   * @param like like or {@code null} for none
   */
  public Answers setLike(java.lang.String like) {
    this.like = like;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getQuestionId() {
    return questionId;
  }

  /**
   * @param questionId questionId or {@code null} for none
   */
  public Answers setQuestionId(java.lang.String questionId) {
    this.questionId = questionId;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getTopic() {
    return topic;
  }

  /**
   * @param topic topic or {@code null} for none
   */
  public Answers setTopic(java.lang.String topic) {
    this.topic = topic;
    return this;
  }

  @Override
  public Answers set(String fieldName, Object value) {
    return (Answers) super.set(fieldName, value);
  }

  @Override
  public Answers clone() {
    return (Answers) super.clone();
  }

}
