/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-04-15 19:10:39 UTC)
 * on 2014-05-13 at 13:39:10 UTC 
 * Modify at your own risk.
 */

package com.farming.app.frontEnd.answersendpoint;

/**
 * Service definition for Answersendpoint (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link AnswersendpointRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Answersendpoint extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.16.0-rc of the answersendpoint library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://farmsocialapp.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "answersendpoint/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Answersendpoint(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Answersendpoint(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "getAnswers".
   *
   * This request holds the parameters needed by the the answersendpoint server.  After setting any
   * optional parameters, call the {@link GetAnswers#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetAnswers getAnswers(java.lang.String id) throws java.io.IOException {
    GetAnswers result = new GetAnswers(id);
    initialize(result);
    return result;
  }

  public class GetAnswers extends AnswersendpointRequest<com.farming.app.frontEnd.answersendpoint.model.Answers> {

    private static final String REST_PATH = "answers/{id}";

    /**
     * Create a request for the method "getAnswers".
     *
     * This request holds the parameters needed by the the answersendpoint server.  After setting any
     * optional parameters, call the {@link GetAnswers#execute()} method to invoke the remote
     * operation. <p> {@link
     * GetAnswers#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetAnswers(java.lang.String id) {
      super(Answersendpoint.this, "GET", REST_PATH, null, com.farming.app.frontEnd.answersendpoint.model.Answers.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetAnswers setAlt(java.lang.String alt) {
      return (GetAnswers) super.setAlt(alt);
    }

    @Override
    public GetAnswers setFields(java.lang.String fields) {
      return (GetAnswers) super.setFields(fields);
    }

    @Override
    public GetAnswers setKey(java.lang.String key) {
      return (GetAnswers) super.setKey(key);
    }

    @Override
    public GetAnswers setOauthToken(java.lang.String oauthToken) {
      return (GetAnswers) super.setOauthToken(oauthToken);
    }

    @Override
    public GetAnswers setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetAnswers) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetAnswers setQuotaUser(java.lang.String quotaUser) {
      return (GetAnswers) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetAnswers setUserIp(java.lang.String userIp) {
      return (GetAnswers) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public GetAnswers setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public GetAnswers set(String parameterName, Object value) {
      return (GetAnswers) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "insertAnswers".
   *
   * This request holds the parameters needed by the the answersendpoint server.  After setting any
   * optional parameters, call the {@link InsertAnswers#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.farming.app.frontEnd.answersendpoint.model.Answers}
   * @return the request
   */
  public InsertAnswers insertAnswers(com.farming.app.frontEnd.answersendpoint.model.Answers content) throws java.io.IOException {
    InsertAnswers result = new InsertAnswers(content);
    initialize(result);
    return result;
  }

  public class InsertAnswers extends AnswersendpointRequest<com.farming.app.frontEnd.answersendpoint.model.Answers> {

    private static final String REST_PATH = "answers";

    /**
     * Create a request for the method "insertAnswers".
     *
     * This request holds the parameters needed by the the answersendpoint server.  After setting any
     * optional parameters, call the {@link InsertAnswers#execute()} method to invoke the remote
     * operation. <p> {@link InsertAnswers#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.farming.app.frontEnd.answersendpoint.model.Answers}
     * @since 1.13
     */
    protected InsertAnswers(com.farming.app.frontEnd.answersendpoint.model.Answers content) {
      super(Answersendpoint.this, "POST", REST_PATH, content, com.farming.app.frontEnd.answersendpoint.model.Answers.class);
    }

    @Override
    public InsertAnswers setAlt(java.lang.String alt) {
      return (InsertAnswers) super.setAlt(alt);
    }

    @Override
    public InsertAnswers setFields(java.lang.String fields) {
      return (InsertAnswers) super.setFields(fields);
    }

    @Override
    public InsertAnswers setKey(java.lang.String key) {
      return (InsertAnswers) super.setKey(key);
    }

    @Override
    public InsertAnswers setOauthToken(java.lang.String oauthToken) {
      return (InsertAnswers) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertAnswers setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertAnswers) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertAnswers setQuotaUser(java.lang.String quotaUser) {
      return (InsertAnswers) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertAnswers setUserIp(java.lang.String userIp) {
      return (InsertAnswers) super.setUserIp(userIp);
    }

    @Override
    public InsertAnswers set(String parameterName, Object value) {
      return (InsertAnswers) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listAnswers".
   *
   * This request holds the parameters needed by the the answersendpoint server.  After setting any
   * optional parameters, call the {@link ListAnswers#execute()} method to invoke the remote
   * operation.
   *
   * @return the request
   */
  public ListAnswers listAnswers() throws java.io.IOException {
    ListAnswers result = new ListAnswers();
    initialize(result);
    return result;
  }

  public class ListAnswers extends AnswersendpointRequest<com.farming.app.frontEnd.answersendpoint.model.CollectionResponseAnswers> {

    private static final String REST_PATH = "answers";

    /**
     * Create a request for the method "listAnswers".
     *
     * This request holds the parameters needed by the the answersendpoint server.  After setting any
     * optional parameters, call the {@link ListAnswers#execute()} method to invoke the remote
     * operation. <p> {@link
     * ListAnswers#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @since 1.13
     */
    protected ListAnswers() {
      super(Answersendpoint.this, "GET", REST_PATH, null, com.farming.app.frontEnd.answersendpoint.model.CollectionResponseAnswers.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListAnswers setAlt(java.lang.String alt) {
      return (ListAnswers) super.setAlt(alt);
    }

    @Override
    public ListAnswers setFields(java.lang.String fields) {
      return (ListAnswers) super.setFields(fields);
    }

    @Override
    public ListAnswers setKey(java.lang.String key) {
      return (ListAnswers) super.setKey(key);
    }

    @Override
    public ListAnswers setOauthToken(java.lang.String oauthToken) {
      return (ListAnswers) super.setOauthToken(oauthToken);
    }

    @Override
    public ListAnswers setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListAnswers) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListAnswers setQuotaUser(java.lang.String quotaUser) {
      return (ListAnswers) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListAnswers setUserIp(java.lang.String userIp) {
      return (ListAnswers) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListAnswers setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListAnswers setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListAnswers set(String parameterName, Object value) {
      return (ListAnswers) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "removeAnswers".
   *
   * This request holds the parameters needed by the the answersendpoint server.  After setting any
   * optional parameters, call the {@link RemoveAnswers#execute()} method to invoke the remote
   * operation.
   *
   * @param id
   * @return the request
   */
  public RemoveAnswers removeAnswers(java.lang.String id) throws java.io.IOException {
    RemoveAnswers result = new RemoveAnswers(id);
    initialize(result);
    return result;
  }

  public class RemoveAnswers extends AnswersendpointRequest<Void> {

    private static final String REST_PATH = "answers/{id}";

    /**
     * Create a request for the method "removeAnswers".
     *
     * This request holds the parameters needed by the the answersendpoint server.  After setting any
     * optional parameters, call the {@link RemoveAnswers#execute()} method to invoke the remote
     * operation. <p> {@link RemoveAnswers#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected RemoveAnswers(java.lang.String id) {
      super(Answersendpoint.this, "DELETE", REST_PATH, null, Void.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public RemoveAnswers setAlt(java.lang.String alt) {
      return (RemoveAnswers) super.setAlt(alt);
    }

    @Override
    public RemoveAnswers setFields(java.lang.String fields) {
      return (RemoveAnswers) super.setFields(fields);
    }

    @Override
    public RemoveAnswers setKey(java.lang.String key) {
      return (RemoveAnswers) super.setKey(key);
    }

    @Override
    public RemoveAnswers setOauthToken(java.lang.String oauthToken) {
      return (RemoveAnswers) super.setOauthToken(oauthToken);
    }

    @Override
    public RemoveAnswers setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (RemoveAnswers) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public RemoveAnswers setQuotaUser(java.lang.String quotaUser) {
      return (RemoveAnswers) super.setQuotaUser(quotaUser);
    }

    @Override
    public RemoveAnswers setUserIp(java.lang.String userIp) {
      return (RemoveAnswers) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String id;

    /**

     */
    public java.lang.String getId() {
      return id;
    }

    public RemoveAnswers setId(java.lang.String id) {
      this.id = id;
      return this;
    }

    @Override
    public RemoveAnswers set(String parameterName, Object value) {
      return (RemoveAnswers) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateAnswers".
   *
   * This request holds the parameters needed by the the answersendpoint server.  After setting any
   * optional parameters, call the {@link UpdateAnswers#execute()} method to invoke the remote
   * operation.
   *
   * @param content the {@link com.farming.app.frontEnd.answersendpoint.model.Answers}
   * @return the request
   */
  public UpdateAnswers updateAnswers(com.farming.app.frontEnd.answersendpoint.model.Answers content) throws java.io.IOException {
    UpdateAnswers result = new UpdateAnswers(content);
    initialize(result);
    return result;
  }

  public class UpdateAnswers extends AnswersendpointRequest<com.farming.app.frontEnd.answersendpoint.model.Answers> {

    private static final String REST_PATH = "answers";

    /**
     * Create a request for the method "updateAnswers".
     *
     * This request holds the parameters needed by the the answersendpoint server.  After setting any
     * optional parameters, call the {@link UpdateAnswers#execute()} method to invoke the remote
     * operation. <p> {@link UpdateAnswers#initialize(com.google.api.client.googleapis.services.Abstra
     * ctGoogleClientRequest)} must be called to initialize this instance immediately after invoking
     * the constructor. </p>
     *
     * @param content the {@link com.farming.app.frontEnd.answersendpoint.model.Answers}
     * @since 1.13
     */
    protected UpdateAnswers(com.farming.app.frontEnd.answersendpoint.model.Answers content) {
      super(Answersendpoint.this, "PUT", REST_PATH, content, com.farming.app.frontEnd.answersendpoint.model.Answers.class);
    }

    @Override
    public UpdateAnswers setAlt(java.lang.String alt) {
      return (UpdateAnswers) super.setAlt(alt);
    }

    @Override
    public UpdateAnswers setFields(java.lang.String fields) {
      return (UpdateAnswers) super.setFields(fields);
    }

    @Override
    public UpdateAnswers setKey(java.lang.String key) {
      return (UpdateAnswers) super.setKey(key);
    }

    @Override
    public UpdateAnswers setOauthToken(java.lang.String oauthToken) {
      return (UpdateAnswers) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateAnswers setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateAnswers) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateAnswers setQuotaUser(java.lang.String quotaUser) {
      return (UpdateAnswers) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateAnswers setUserIp(java.lang.String userIp) {
      return (UpdateAnswers) super.setUserIp(userIp);
    }

    @Override
    public UpdateAnswers set(String parameterName, Object value) {
      return (UpdateAnswers) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Answersendpoint}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Answersendpoint}. */
    @Override
    public Answersendpoint build() {
      return new Answersendpoint(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link AnswersendpointRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setAnswersendpointRequestInitializer(
        AnswersendpointRequestInitializer answersendpointRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(answersendpointRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
